// examples/basic-server-solid/src/mcp-app.tsx
/**
 * @file App that demonstrates a few features using MCP Apps SDK + Solid.
 */
import {
  App,
  applyDocumentTheme,
  applyHostFonts,
  applyHostStyleVariables,
  type McpUiHostContext,
} from "@modelcontextprotocol/ext-apps";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { createEffect, createSignal, onMount, Show } from "solid-js";
import { render } from "solid-js/web";
import styles from "./mcp-app.module.css";

function extractTime(callToolResult: CallToolResult): string {
  const { text } = callToolResult.content?.find((c) => c.type === "text")!;
  return text;
}


function GetTimeApp() {
  const [app, setApp] = createSignal<App | null>(null);
  const [error, setError] = createSignal<Error | null>(null);
  const [toolResult, setToolResult] = createSignal<CallToolResult | null>(null);
  const [hostContext, setHostContext] = createSignal<McpUiHostContext | undefined>();

  // Apply host styles reactively when hostContext changes
  createEffect(() => {
    const ctx = hostContext();
    if (ctx?.theme) {
      applyDocumentTheme(ctx.theme);
    }
    if (ctx?.styles?.variables) {
      applyHostStyleVariables(ctx.styles.variables);
    }
    if (ctx?.styles?.css?.fonts) {
      applyHostFonts(ctx.styles.css.fonts);
    }
  });

  onMount(async () => {
    const instance = new App({ name: "Get Time App", version: "1.0.0" });

    instance.ontoolinput = async (input) => {
      console.info("Received tool call input:", input);
    };

    instance.ontoolresult = async (result) => {
      console.info("Received tool call result:", result);
      setToolResult(result);
    };

    instance.ontoolcancelled = (params) => {
      console.info("Tool call cancelled:", params.reason);
    };

    instance.onerror = console.error;

    instance.onhostcontextchanged = (params) => {
      setHostContext((prev) => ({ ...prev, ...params }));
    };

    try {
      await instance.connect();
      setApp(instance);
      setHostContext(instance.getHostContext());
    } catch (e) {
      setError(e as Error);
    }
  });

  return (
    <Show when={!error()} fallback={<div><strong>ERROR:</strong> {error()!.message}</div>}>
      <Show when={app()} fallback={<div>Connecting...</div>}>
        <GetTimeAppInner app={app()!} toolResult={toolResult()} hostContext={hostContext()} />
      </Show>
    </Show>
  );
}


interface GetTimeAppInnerProps {
  app: App;
  toolResult: CallToolResult | null;
  hostContext?: McpUiHostContext;
}
function GetTimeAppInner(props: GetTimeAppInnerProps) {
  const [serverTime, setServerTime] = createSignal("Loading...");
  const [messageText, setMessageText] = createSignal("This is message text.");
  const [logText, setLogText] = createSignal("This is log text.");
  const [linkUrl, setLinkUrl] = createSignal("https://modelcontextprotocol.io/");

  // Update serverTime when toolResult changes
  createEffect(() => {
    if (props.toolResult) {
      setServerTime(extractTime(props.toolResult));
    }
  });

  async function handleGetTime() {
    try {
      console.info("Calling get-time tool...");
      const result = await props.app.callServerTool({ name: "get-time", arguments: {} });
      console.info("get-time result:", result);
      setServerTime(extractTime(result));
    } catch (e) {
      console.error(e);
      setServerTime("[ERROR]");
    }
  }

  async function handleSendMessage() {
    const signal = AbortSignal.timeout(5000);
    try {
      console.info("Sending message text to Host:", messageText());
      const { isError } = await props.app.sendMessage(
        { role: "user", content: [{ type: "text", text: messageText() }] },
        { signal },
      );
      console.info("Message", isError ? "rejected" : "accepted");
    } catch (e) {
      console.error("Message send error:", signal.aborted ? "timed out" : e);
    }
  }

  async function handleSendLog() {
    console.info("Sending log text to Host:", logText());
    await props.app.sendLog({ level: "info", data: logText() });
  }

  async function handleOpenLink() {
    console.info("Sending open link request to Host:", linkUrl());
    const { isError } = await props.app.openLink({ url: linkUrl() });
    console.info("Open link request", isError ? "rejected" : "accepted");
  }

  return (
    <main
      class={styles.main}
      style={props.hostContext?.safeAreaInsets ? {
        "padding-top": `${props.hostContext.safeAreaInsets.top}px`,
        "padding-right": `${props.hostContext.safeAreaInsets.right}px`,
        "padding-bottom": `${props.hostContext.safeAreaInsets.bottom}px`,
        "padding-left": `${props.hostContext.safeAreaInsets.left}px`,
      } : undefined}
    >
      <p class={styles.notice}>Watch activity in the DevTools console!</p>

      <div class={styles.action}>
        <p>
          <strong>Server Time:</strong> <code class={styles.serverTime}>{serverTime()}</code>
        </p>
        <button onClick={handleGetTime}>Get Server Time</button>
      </div>

      <div class={styles.action}>
        <textarea value={messageText()} onInput={(e) => setMessageText(e.currentTarget.value)} />
        <button onClick={handleSendMessage}>Send Message</button>
      </div>

      <div class={styles.action}>
        <input type="text" value={logText()} onInput={(e) => setLogText(e.currentTarget.value)} />
        <button onClick={handleSendLog}>Send Log</button>
      </div>

      <div class={styles.action}>
        <input type="url" value={linkUrl()} onInput={(e) => setLinkUrl(e.currentTarget.value)} />
        <button onClick={handleOpenLink}>Open Link</button>
      </div>
    </main>
  );
}


render(() => <GetTimeApp />, document.getElementById("root")!);

// examples/integration-server/src/mcp-app.tsx
/**
 * @file App that demonstrates a few features using MCP Apps SDK + React.
 */
import type { App, McpUiHostContext } from "@modelcontextprotocol/ext-apps";
import { useApp } from "@modelcontextprotocol/ext-apps/react";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { StrictMode, useCallback, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import styles from "./mcp-app.module.css";

const IMPLEMENTATION = { name: "Get Time App", version: "1.0.0" };

const log = {
  info: console.log.bind(console, "[APP]"),
  warn: console.warn.bind(console, "[APP]"),
  error: console.error.bind(console, "[APP]"),
};

function extractTime(callToolResult: CallToolResult): string {
  const { time } = callToolResult.structuredContent as { time: string };
  return time;
}

function GetTimeApp() {
  const [toolResult, setToolResult] = useState<CallToolResult | null>(null);
  const [hostContext, setHostContext] = useState<
    McpUiHostContext | undefined
  >();
  const { app, error } = useApp({
    appInfo: IMPLEMENTATION,
    capabilities: {},
    onAppCreated: (app) => {
      app.onteardown = async () => {
        log.info("App is being torn down");
        await new Promise((resolve) => setTimeout(resolve, 500)); // Simulate cleanup work
        log.info("App teardown complete");
        return {};
      };
      app.ontoolinput = async (input) => {
        log.info("Received tool call input:", input);
      };

      app.ontoolresult = async (result) => {
        log.info("Received tool call result:", result);
        setToolResult(result);
      };

      app.onerror = log.error;

      app.onhostcontextchanged = (params) => {
        setHostContext((prev) => ({ ...prev, ...params }));
      };
    },
  });

  useEffect(() => {
    if (app) {
      setHostContext(app.getHostContext());
    }
  }, [app]);

  if (error)
    return (
      <div>
        <strong>ERROR:</strong> {error.message}
      </div>
    );
  if (!app) return <div>Connecting...</div>;

  return (
    <GetTimeAppInner
      app={app}
      toolResult={toolResult}
      hostContext={hostContext}
    />
  );
}

interface GetTimeAppInnerProps {
  app: App;
  toolResult: CallToolResult | null;
  hostContext?: McpUiHostContext;
}
function GetTimeAppInner({
  app,
  toolResult,
  hostContext,
}: GetTimeAppInnerProps) {
  const [serverTime, setServerTime] = useState("Loading...");
  const [messageText, setMessageText] = useState("This is message text.");
  const [logText, setLogText] = useState("This is log text.");
  const [linkUrl, setLinkUrl] = useState("https://modelcontextprotocol.io/");

  useEffect(() => {
    if (toolResult) {
      setServerTime(extractTime(toolResult));
    }
  }, [toolResult]);

  const handleGetTime = useCallback(async () => {
    try {
      log.info("Calling get-time tool...");
      const result = await app.callServerTool({
        name: "get-time",
        arguments: {},
      });
      log.info("get-time result:", result);
      setServerTime(extractTime(result));
    } catch (e) {
      log.error(e);
      setServerTime("[ERROR]");
    }
  }, [app]);

  const handleSendMessage = useCallback(async () => {
    const signal = AbortSignal.timeout(5000);
    try {
      log.info("Sending message text to Host:", messageText);
      const { isError } = await app.sendMessage(
        { role: "user", content: [{ type: "text", text: messageText }] },
        { signal },
      );
      log.info("Message", isError ? "rejected" : "accepted");
    } catch (e) {
      log.error("Message send error:", signal.aborted ? "timed out" : e);
    }
  }, [app, messageText]);

  const handleSendLog = useCallback(async () => {
    log.info("Sending log text to Host:", logText);
    await app.sendLog({ level: "info", data: logText });
  }, [app, logText]);

  const handleOpenLink = useCallback(async () => {
    log.info("Sending open link request to Host:", linkUrl);
    const { isError } = await app.openLink({ url: linkUrl });
    log.info("Open link request", isError ? "rejected" : "accepted");
  }, [app, linkUrl]);

  const canDownload = app.getHostCapabilities()?.downloadFile !== undefined;

  const handleDownloadFile = useCallback(async () => {
    const sampleContent = JSON.stringify(
      { time: serverTime, exported: new Date().toISOString() },
      null,
      2,
    );
    log.info("Requesting file download...");
    const { isError } = await app.downloadFile({
      contents: [
        {
          type: "resource",
          resource: {
            uri: "file:///export.json",
            mimeType: "application/json",
            text: sampleContent,
          },
        },
      ],
    });
    log.info("Download", isError ? "rejected" : "accepted");
  }, [app, serverTime]);

  const handleDownloadLink = useCallback(async () => {
    log.info("Requesting resource link download...");
    const { isError } = await app.downloadFile({
      contents: [
        {
          type: "resource_link",
          uri: "resource:///sample-report.txt",
          name: "sample-report.txt",
          mimeType: "text/plain",
        },
      ],
    });
    log.info("Resource link download", isError ? "rejected" : "accepted");
  }, [app]);

  return (
    <main
      className={styles.main}
      style={{
        paddingTop: hostContext?.safeAreaInsets?.top,
        paddingRight: hostContext?.safeAreaInsets?.right,
        paddingBottom: hostContext?.safeAreaInsets?.bottom,
        paddingLeft: hostContext?.safeAreaInsets?.left,
      }}
    >
      <p className={styles.notice}>Watch activity in the DevTools console!</p>

      <div className={styles.action}>
        <p>
          <strong>Server Time:</strong>{" "}
          <code className={styles.serverTime}>{serverTime}</code>
        </p>
        <button onClick={handleGetTime}>Get Server Time</button>
      </div>

      <div className={styles.action}>
        <textarea
          value={messageText}
          onChange={(e) => setMessageText(e.target.value)}
        />
        <button onClick={handleSendMessage}>Send Message</button>
      </div>

      <div className={styles.action}>
        <input
          type="text"
          value={logText}
          onChange={(e) => setLogText(e.target.value)}
        />
        <button onClick={handleSendLog}>Send Log</button>
      </div>

      <div className={styles.action}>
        <input
          type="url"
          value={linkUrl}
          onChange={(e) => setLinkUrl(e.target.value)}
        />
        <button onClick={handleOpenLink}>Open Link</button>
      </div>

      {canDownload && (
        <div className={styles.action}>
          <p>Download file via EmbeddedResource or ResourceLink</p>
          <div style={{ display: "flex", gap: "8px" }}>
            <button onClick={handleDownloadFile}>Embedded</button>
            <button onClick={handleDownloadLink}>Link</button>
          </div>
        </div>
      )}
    </main>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <GetTimeApp />
  </StrictMode>,
);
